[package]
name = "rokkakari"
version = "0.1.0"
authors = ["Jim Gerth <jim.frederic.gerth@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3.1"
